
CREATE DATABASE chart_test;

GRANT ALL ON chart_test.* TO chart_user@localhost IDENTIFIED BY 'chart_user';

use chart_test;

create table data_series (
    id bigint auto_increment,
    series_name varchar(80) not null,
    primary key(id),
    unique(series_name)
);

create table data_point (
    id bigint auto_increment,
    ts timestamp not null,
    data_series_id bigint not null,
    value float not null,
    primary key(id),
    constraint foreign key (data_series_id) references data_series(id)
);



/*** for oracle 11*/

create sequence data_series_seq start with 1;
create sequence data_point_seq  start with 1;


create table data_series (
    id number not null,
    series_name varchar2(80) not null,
    primary key(id),
    unique(series_name)
);

create table data_point (
    id number not null,
    ts timestamp not null,
    data_series_id number not null,
    value float not null,
    primary key(id),
    constraint FK_DP_DS foreign key (data_series_id) references data_series(id)
);



create or replace trigger data_series_bir 
before insert on data_series 
for each row

begin
    select data_series_seq.nextval
    into   :new.id
    from   dual;
end;
/

create or replace trigger data_point_bir 
before insert on data_point 
for each row

begin
    select data_point_seq.nextval
    into   :new.id
    from   dual;
end;
/


/*** for oracle 12*/


create table data_series (
    id  NUMBER GENERATED ALWAYS as IDENTITY,
    series_name varchar2(80) not null,
    primary key(id),
    unique(series_name)
);

create table data_point (
    id  NUMBER GENERATED by default on null as IDENTITY,
    ts timestamp not null,
    data_series_id number not null,
    value float not null,
    primary key(id),
    constraint foreign key (data_series_id) references data_series(id)
);
